name: lcq
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - absl-py=2.1.0=py311h06a4308_0
  - alembic=1.8.0=pyhd8ed1ab_0
  - asttokens=2.4.1=pyhd8ed1ab_0
  - atk-1.0=2.36.0=ha1a6a79_0
  - bayesian-optimization=2.0.0=pyhd8ed1ab_0
  - blas=1.0=mkl
  - boost-cpp=1.82.0=hdb19cb5_2
  - bottleneck=1.3.7=py311hf4808d0_0
  - brotli=1.0.9=h5eee18b_8
  - brotli-bin=1.0.9=h5eee18b_8
  - brotli-python=1.0.9=py311h6a678d5_8
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - cairo=1.16.0=hb05425b_5
  - certifi=2025.10.5=pyhd8ed1ab_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - colorlog=6.9.0=pyh707e725_0
  - comm=0.2.2=pyhd8ed1ab_0
  - contourpy=1.3.1=py311hdb19cb5_0
  - cuda-cudart=12.4.127=h99ab3db_0
  - cuda-cudart_linux-64=12.4.127=hd681fbe_0
  - cuda-cupti=12.4.127=h6a678d5_1
  - cuda-libraries=12.4.1=h06a4308_1
  - cuda-nvrtc=12.4.127=h99ab3db_1
  - cuda-nvtx=12.4.127=h6a678d5_1
  - cuda-opencl=12.4.127=h6a678d5_0
  - cuda-runtime=12.4.1=hb982923_0
  - cuda-version=12.4=hbda6634_3
  - cycler=0.11.0=pyhd3eb1b0_0
  - cyrus-sasl=2.1.28=h52b45da_1
  - dbus=1.13.18=hb2f20db_0
  - debugpy=1.6.7=py311h6a678d5_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - exceptiongroup=1.2.2=pyhd8ed1ab_0
  - executing=2.1.0=pyhd8ed1ab_0
  - expat=2.6.3=h6a678d5_0
  - ffmpeg=4.3=hf484d3e_0
  - filelock=3.13.1=py311h06a4308_0
  - font-ttf-dejavu-sans-mono=2.37=hd3eb1b0_0
  - font-ttf-inconsolata=2.001=hcb22688_0
  - font-ttf-source-code-pro=2.030=hd3eb1b0_0
  - font-ttf-ubuntu=0.83=h8b1ccd4_0
  - fontconfig=2.14.1=h55d465d_3
  - fonts-anaconda=1=h8fa9717_0
  - fonts-conda-ecosystem=1=hd3eb1b0_0
  - fonttools=4.51.0=py311h5eee18b_0
  - freetype=2.12.1=h4a9f257_0
  - fribidi=1.0.10=h7b6447c_0
  - gdk-pixbuf=2.42.10=h5eee18b_1
  - giflib=5.2.2=h5eee18b_0
  - glib=2.78.4=h6a678d5_0
  - glib-tools=2.78.4=h6a678d5_0
  - gmp=6.2.1=h295c915_3
  - gmpy2=2.1.2=py311hc9b5ff0_0
  - gnutls=3.6.15=he1e5248_0
  - gobject-introspection=1.78.1=py311h42194e9_1
  - graphite2=1.3.14=h295c915_1
  - graphviz=2.50.0=h1b29801_1
  - greenlet=3.0.1=py311h6a678d5_0
  - gst-plugins-base=1.14.1=h6a678d5_1
  - gstreamer=1.14.1=h5eee18b_1
  - gtk2=2.24.33=h73c1081_2
  - gts=0.7.6=hb67d8dd_3
  - harfbuzz=4.3.0=hf52aaf7_2
  - icu=73.1=h6a678d5_0
  - idna=3.7=py311h06a4308_0
  - importlib-metadata=8.5.0=pyha770c72_0
  - importlib_resources=6.4.5=pyhd8ed1ab_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - ipykernel=6.29.5=pyh3099207_0
  - ipython=8.29.0=pyh707e725_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - jinja2=3.1.4=py311h06a4308_0
  - joblib=1.4.2=pyhd8ed1ab_0
  - jpeg=9e=h5eee18b_3
  - jupyter_client=8.6.3=pyhd8ed1ab_0
  - jupyter_core=5.7.2=pyh31011fe_1
  - kiwisolver=1.4.4=py311h6a678d5_0
  - krb5=1.20.1=h143b758_1
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=3.0=h295c915_0
  - libabseil=20240116.2=cxx17_h6a678d5_0
  - libboost=1.82.0=h109eef0_2
  - libbrotlicommon=1.0.9=h5eee18b_8
  - libbrotlidec=1.0.9=h5eee18b_8
  - libbrotlienc=1.0.9=h5eee18b_8
  - libclang=14.0.6=default_hc6dbbc7_1
  - libclang13=14.0.6=default_he11475f_1
  - libcublas=12.4.5.8=h99ab3db_1
  - libcufft=11.2.1.3=h99ab3db_1
  - libcufile=1.9.1.3=h99ab3db_1
  - libcups=2.4.2=h2d74bed_1
  - libcurand=10.3.5.147=h99ab3db_1
  - libcurl=8.9.1=h251f7ec_0
  - libcusolver=11.6.1.9=h99ab3db_1
  - libcusparse=12.3.1.170=h99ab3db_1
  - libdeflate=1.17=h5eee18b_1
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgd=2.3.3=h695aa2c_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libglib=2.78.4=hdc74915_0
  - libgomp=11.2.0=h1234567_1
  - libgrpc=1.62.2=h2d74bed_0
  - libiconv=1.16=h5eee18b_3
  - libidn2=2.3.4=h5eee18b_0
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - libllvm14=14.0.6=hecde1de_4
  - libnghttp2=1.57.0=h2d74bed_0
  - libnpp=12.2.5.30=h99ab3db_1
  - libnvfatbin=12.4.127=h7934f7d_2
  - libnvjitlink=12.4.127=h99ab3db_1
  - libnvjpeg=12.3.1.117=h6a678d5_1
  - libpng=1.6.39=h5eee18b_0
  - libpq=12.17=hdbd6064_0
  - libprotobuf=4.25.3=he621ea3_0
  - librsvg=2.54.4=haac4a5d_4
  - libsodium=1.0.18=h36c2ea0_1
  - libssh2=1.11.0=h251f7ec_0
  - libstdcxx-ng=13.2.0=hc0a3c3a_7
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.5.1=h6a678d5_0
  - libtool=2.4.6=h6a678d5_1009
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp=1.3.2=h11a3e52_0
  - libwebp-base=1.3.2=h5eee18b_1
  - libxcb=1.15=h7f8727e_0
  - libxkbcommon=1.0.1=h097e994_2
  - libxml2=2.13.1=hfdd30dd_2
  - lightgbm=4.5.0=py311h6a678d5_0
  - llvm-openmp=14.0.6=h9e868ea_0
  - lz4-c=1.9.4=h6a678d5_1
  - mako=1.3.5=pyhd8ed1ab_0
  - markdown=3.4.1=py311h06a4308_0
  - markupsafe=2.1.3=py311h5eee18b_0
  - matplotlib=3.9.2=py311h06a4308_0
  - matplotlib-base=3.9.2=py311h6fb44e5_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py311h5eee18b_1
  - mkl_fft=1.3.10=py311h5eee18b_0
  - mkl_random=1.2.7=py311ha02d727_0
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.2=hb69a4c5_1
  - mpmath=1.3.0=py311h06a4308_0
  - mysql=5.7.24=h721c034_2
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=3.3=py311h06a4308_0
  - ninja=1.12.1=h06a4308_0
  - ninja-base=1.12.1=hdb19cb5_0
  - nspr=4.35=h6a678d5_0
  - nss=3.89.1=h6a678d5_0
  - numexpr=2.10.1=py311h3c60e43_0
  - numpy=1.26.4=py311h08b1b3b_0
  - numpy-base=1.26.4=py311hf175353_0
  - ocl-icd=2.3.2=h5eee18b_1
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.5.2=he7f1fd0_0
  - openssl=3.0.17=h5eee18b_0
  - optuna=4.1.0=pyhd8ed1ab_0
  - packaging=24.1=pyhd8ed1ab_0
  - pango=1.50.7=h05da053_0
  - parso=0.8.4=pyhd8ed1ab_0
  - pcre2=10.42=hebb0a14_1
  - pexpect=4.9.0=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pillow=10.4.0=py311h5eee18b_0
  - pip=24.2=py311h06a4308_0
  - pixman=0.40.0=h7f8727e_1
  - platformdirs=4.3.6=pyhd8ed1ab_0
  - ply=3.11=py311h06a4308_0
  - poppler=22.12.0=h9614445_3
  - poppler-data=0.4.11=h06a4308_1
  - prompt-toolkit=3.0.48=pyha770c72_0
  - psutil=5.9.0=py311h5eee18b_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.3=pyhd8ed1ab_0
  - pybind11-abi=4=hd8ed1ab_3
  - pygments=2.18.0=pyhd8ed1ab_0
  - pyparsing=3.1.2=py311h06a4308_0
  - pyqt=5.15.10=py311h6a678d5_0
  - pyqt5-sip=12.13.0=py311h5eee18b_0
  - pysocks=1.7.1=py311h06a4308_0
  - python=3.11.10=he870216_0
  - python-dateutil=2.9.0=pyhd8ed1ab_0
  - python-graphviz=0.20.1=py311h06a4308_0
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - pytorch-cuda=12.4=hc786d27_7
  - pytorch-mutex=1.0=cuda
  - pyyaml=6.0.2=py311h5eee18b_0
  - pyzmq=25.1.2=py311h6a678d5_0
  - qt-main=5.15.2=h53bd1ea_10
  - re2=2022.04.01=h295c915_0
  - readline=8.2=h5eee18b_0
  - requests=2.32.3=py311h06a4308_0
  - seaborn=0.13.2=py311h06a4308_0
  - setuptools=75.1.0=py311h06a4308_0
  - sip=6.7.12=py311h6a678d5_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlalchemy=1.4.51=py311h5eee18b_0
  - sqlite=3.45.3=h5eee18b_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - sympy=1.13.2=py311h06a4308_0
  - tbb=2021.8.0=hdb19cb5_0
  - tensorboard=2.17.0=py311h06a4308_0
  - tensorboard-data-server=0.7.0=py311h52d8a92_1
  - threadpoolctl=3.5.0=pyhc1e730c_0
  - tk=8.6.14=h39e8969_0
  - tornado=6.4.1=py311h5eee18b_0
  - tqdm=4.66.6=pyhd8ed1ab_0
  - traitlets=5.14.3=pyhd8ed1ab_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - unicodedata2=15.1.0=py311h5eee18b_0
  - urllib3=2.2.3=py311h06a4308_0
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - werkzeug=3.0.3=py311h06a4308_0
  - wheel=0.44.0=py311h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - zeromq=4.3.5=h6a678d5_0
  - zipp=3.20.2=pyhd8ed1ab_0
  - zlib=1.2.13=h5eee18b_1
  - zstd=1.5.6=hc292b87_0
  - pip:
      - aeon==1.0.0
      - aiohappyeyeballs==2.4.6
      - aiohttp==3.11.12
      - aiosignal==1.3.2
      - annotated-types==0.7.0
      - anyio==4.6.2.post1
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - args==0.1.0
      - arrow==1.3.0
      - async-lru==2.0.4
      - attrs==24.2.0
      - babel==2.16.0
      - beautifulsoup4==4.12.3
      - bleach==6.2.0
      - blis==1.0.1
      - cachetools==5.5.0
      - catalogue==2.0.10
      - cffi==1.17.1
      - click==8.1.7
      - clint==0.5.1
      - cloudpathlib==0.20.0
      - cloudpickle==3.1.0
      - confection==0.1.5
      - coverage==7.6.8
      - cymem==2.0.10
      - defusedxml==0.7.1
      - deprecated==1.2.15
      - dgl==2.0.0+cu121
      - fastai==2.7.18
      - fastcore==1.7.22
      - fastdownload==0.0.7
      - fastjsonschema==2.20.0
      - fastprogress==1.0.3
      - fqdn==1.5.1
      - frozendict==2.4.6
      - frozenlist==1.5.0
      - fsspec==2024.10.0
      - future==1.0.0
      - google-ai-generativelanguage==0.6.10
      - google-api-core==2.24.0
      - google-api-python-client==2.157.0
      - google-auth==2.37.0
      - google-auth-httplib2==0.2.0
      - google-generativeai==0.8.3
      - googleapis-common-protos==1.66.0
      - grpcio==1.69.0
      - grpcio-status==1.69.0
      - h11==0.14.0
      - html5lib==1.1
      - httpcore==1.0.7
      - httplib2==0.22.0
      - httpx==0.27.2
      - hyperopt==0.2.7
      - imbalanced-learn==0.12.4
      - ipywidgets==8.1.5
      - isoduration==20.11.0
      - json5==0.9.28
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - jupyter==1.1.1
      - jupyter-console==6.6.3
      - jupyter-events==0.10.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.14.2
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.2.6
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - jupyterlab-widgets==3.0.13
      - langcodes==3.5.0
      - language-data==1.3.0
      - llvmlite==0.43.0
      - lxml==5.3.0
      - mamba==0.11.3
      - marisa-trie==1.2.1
      - markdown-it-py==3.0.0
      - mdurl==0.1.2
      - mistune==3.0.2
      - multidict==6.1.0
      - multitasking==0.0.11
      - murmurhash==1.0.11
      - nbclient==0.10.0
      - nbconvert==7.16.4
      - nbformat==5.10.4
      - netron==8.0.7
      - notebook==7.2.2
      - notebook-shim==0.2.4
      - numba==0.60.0
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.19.3
      - nvidia-nvjitlink-cu12==12.6.85
      - nvidia-nvtx-cu12==12.1.105
      - onnx==1.17.0
      - opt-einsum==3.4.0
      - overrides==7.7.0
      - pandas==2.2.3
      - pandocfilters==1.5.1
      - patsy==1.0.1
      - peewee==3.17.7
      - pgmpy==0.1.26
      - preshed==3.0.9
      - prometheus-client==0.21.0
      - propcache==0.2.1
      - proto-plus==1.25.0
      - protobuf==5.29.2
      - py4j==0.10.9.7
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.1
      - pycparser==2.22
      - pydantic==2.10.3
      - pydantic-core==2.27.1
      - pygraphviz==1.14
      - python-json-logger==2.0.7
      - pyts==0.13.0
      - pytz==2024.2
      - referencing==0.35.1
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rich==13.9.4
      - rpds-py==0.21.0
      - rsa==4.9
      - scikit-base==0.11.0
      - scikit-learn==1.5.2
      - scipy==1.14.1
      - send2trash==1.8.3
      - shellingham==1.5.4
      - sktime==0.34.1
      - smart-open==7.0.5
      - sniffio==1.3.1
      - soupsieve==2.6
      - spacy==3.8.2
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.5
      - srsly==2.4.8
      - statsmodels==0.14.4
      - terminado==0.18.1
      - thinc==8.3.2
      - tinycss2==1.4.0
      - torch==2.1.1+cu121
      - torchaudio==2.1.1+cu121
      - torchdata==0.7.1
      - torchvision==0.16.1+cu121
      - triton==2.1.0
      - tsai==0.3.9
      - typer==0.15.0
      - types-python-dateutil==2.9.0.20241003
      - typing-extensions==4.12.2
      - tzdata==2024.2
      - uri-template==1.3.0
      - uritemplate==4.1.1
      - wasabi==1.1.3
      - weasel==0.4.1
      - webcolors==24.11.1
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - widgetsnbextension==4.0.13
      - wrapt==1.17.0
      - xgboost==2.1.2
      - yarl==1.18.3
      - yfinance==0.2.48
prefix: /home/lcq/ENTER/envs/lcq
